prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hdrn: <http://purl.obolibrary.org/obo/HDRN#HDRNv1>

SELECT ?label ?def
WHERE {
  ?cls a owl:Class .
  ?cls rdfs:label ?label .
  OPTIONAL {?cls def: ?def}  .
  FILTER EXISTS {?cls oio:inSubset hdrn:}
  }
ORDER BY ?label